language: python
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8

install:
  - "pip install tox"
  - "pip install coveralls"

script: tox

after_success: coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.net#goatd"
    template:
      - "%{repository}/%{branch} [%{commit}] %{author}: %{message}"
      - "Build #%{build_number}: %{build_url}"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
