language: python
sudo: false
env:
- TOXENV=py27
- TOXENV=py34
- TOXENV=pypy
- TOXENV=flake8
install:
- pip install tox
- pip install coveralls
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: kragniz
  password:
    secure: E8SrBVjlFs9Vi5Cd59hCX3ravzLJKgxCq732JHAavUVw3IC2PPU+7lz4GhxSUEMu0yclK9t756LS/drQCGdw955s4eC0A6h8AYwWE4NRtwnRlOsQ/MieT3aAwl/dlY2F3OjNMHkpEQPF6YqcDhrUsIXfyJ318q+Hepb7Q1BGVuI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: goatd/goatd
